### ISSUE TITLE
Consider reading it more vividly

### ISSUE THREAD

**Issue by ao-jo** [JonAlb/ScrumGuideMp3#3]
Thanks for sharing that recording. I like it and would benefit from it even more if you'd read a little more vividly. I know this is quite general and subjective feedback...

**Comment by AllAgile** [comment]
Would need to re-record the whole guide, are there specific sections that could do more vividity, or is it across the piece?

**Comment by ao-jo** [comment]
I listened through the first 10 minutes, and I assume the remaining 30 minutes are similar. I wouldn't re-record everything, especially since you did it primarily for you to learn.
